Update torch in order to make PPC64 work
Note: If your compilation breaks like below:
torch-distro/pkg/torch/lib/TH/vector/VSX.c:983:1: internal compiler
error: in extract_insn, at recog.c:2287

Then it's because you used the latest gcc-6, try v4.8 or v5.